project_name/views/field.py
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import Blueprint, render_template, jsonify, redirect, url_for, request, g, session
from re import escape
from project_name.views.misc import items_pagebar
from project_name.extension import mysql


mod = Blueprint('field', __name__)


@mod.route('/')
@mod.route('/simple_list', methods=['GET', 'POST'])
@mod.route('/simple_list/<int:page>/<int:items>', methods=['GET', 'POST'])
def simple_list(page=0, items=10):
    """簡單的field列表
    查出依條件查出 符合條件的資料
    可能有 LIMIT <from>,<how many>
    可能有 SORY BY <column> ASC/DESC
    然後 assign 給 html
    有一些經過標準計算取得的數值要 assign 給清單控制分頁用
    """
    conn = mysql.get_db()

    # 先取得符合條件的 record 一共有多少筆
    sql1 = u"SELECT COUNT(*) as total FROM field"
    with conn.cursor() as cursor:
        cursor.execute(sql1)
        row = cursor.fetchone()
        total = row[0]
    print(total)

    sort_condition = u""
    if 'sort' in request.args and 'asc' in request.args:  # 檢查是否同時提供排序的目標欄位及排序方法
        sort_condition = u" ORDER BY {0} ".format(request.args.get('sort'))
        if request.args.get('asc') == '0':  # 表示不要asc, 即desc
            sort_condition += u" DESC"
        else:  # 表示要asc
            sort_condition += u" ASC"

    sql2 = u"SELECT * FROM field" + sort_condition
    skip = page * items
    if skip >= total:
        skip = 0
    sql2 += u" LIMIT {0},{1}".format(skip, items)
    print(sql2)

    # 執行 sql2 取得資料 (多筆)
    fields = []
    with conn.cursor() as cursor:
        cursor.execute(sql2)
        fields = cursor.fetchall()
    print(fields)

    misc = items_pagebar(total, page, items)  # 計算pagebar需要之參數

    return render_template('field/list.html', fields=fields, misc=misc, action='simple_list')


@mod.route('/search', methods=['GET', 'POST'])
@mod.route('/search/<int:page>/<int:items>', methods=['GET', 'POST'])
def search(page=0, items=10):
    """加入搜尋條件的field列表
    """
    conn = mysql.get_db()
    query_condition = u""
    if request.method == 'POST' and request.form['s_key'] and request.form['s_value']:
        query_condition = u" WHERE {0} LIKE '%{1}%'".format(request.form['s_key'], request.form['s_value'])
        session['s_key'] = request.form['s_key']
        session['s_value'] = request.form['s_value']
    elif 's_key' in session and 's_value' in session:
        query_condition = u" WHERE {0} LIKE '%{1}%'".format(session['s_key'], session['s_value'])

    if len(query_condition) != 0:
        sql1 = u"SELECT COUNT(*) as total FROM field" + query_condition
        with conn.cursor() as cursor:
            cursor.execute(sql1)
            row = cursor.fetchone()
            total = row[0]
        print(total)

        sort_condition = u""
        if 'sort' in request.args and 'asc' in request.args:  # 檢查是否同時提供排序的目標欄位及排序方法
            sort_condition = u" ORDER BY {0} ".format(request.args.get('sort'))
            if request.args.get('asc') == '0':  # 表示不要asc, 即desc
                sort_condition += u" DESC"
            else:  # 表示要asc
                sort_condition += u" ASC"

        sql2 = u"SELECT * FROM field" + query_condition + sort_condition
        skip = page * items
        if skip >= total:
            skip = 0
        sql2 += u" LIMIT {0},{1}".format(skip, items)

        # 執行 sql2 取得資料 (多筆)
        fields = []
        with conn.cursor() as cursor:
            cursor.execute(sql2)
            fields = cursor.fetchall()
        print(fields)

        misc = items_pagebar(total, page, items)  # 計算pagebar需要之參數
        misc['s_key'] = session['s_key'] or u''
        misc['s_value'] = session['s_value'] or u''
        return render_template('field/list.html', fields=fields, misc=misc, action='search')
    else:
        return redirect(url_for('field.simple_list'))


@mod.route('/view/<field_id>')
def view(field_id):
    """顯示某筆field的頁面與細節
    """
    # 查出單筆, assign給頁面
    conn = mysql.get_db()
    sql = u"SELECT * FROM field WHERE field_id=%s"
    with conn.cursor() as cursor:
        cursor.execute(sql, field_id)
        field = cursor.fetchone()
    return render_template('field/view.html', field=field)


@mod.route('/create', methods=['GET', 'POST'])
def create():
    """新增一筆field資料
    """
    if request.method == 'POST':
        conn = mysql.get_db()
        # 實際寫入一筆
        sql = u"INSERT INTO `field` (`name`, `address`, `status`) VALUES (%s, %s, %s)"
        print(request.form.to_dict())
        post = request.form.to_dict()
        status = 'status' in request.form
        with conn.cursor() as cursor:
            conn.begin()
            cursor.execute(sql, (post['name'],
                                 post['address'],
                                 status)
                           )
            field_id = cursor.lastrowid
            conn.commit()
        return redirect(url_for('field.view', field_id=field_id))
    else:
        return render_template('field/create.html')


@mod.route('/update/<field_id>', methods=['GET', 'POST'])
def update(field_id):
    """修改一筆field資料
    若有post則修改後更新db
    無post則查出field並顯示修改頁
    """
    conn = mysql.get_db()
    if request.method == 'POST':
        # 依 field_id 進行 update
        sql = u"UPDATE field SET `name`=%s, `address`=%s, `modified`=%s, `status`=%s WHERE `field_id`=%s"
        print(request.form.to_dict())
        post = request.form.to_dict()
        status = 'status' in request.form
        with conn.cursor() as cursor:
            conn.begin()
            cursor.execute(sql, (post['name'],
                                 post['address'],
                                 datetime.now(),
                                 status,
                                 field_id)
                           )
            conn.commit()
        return redirect(url_for('field.view', field_id=field_id))
    else:
        # 查出單筆, assign給頁面進行修改
        sql = u"SELECT * FROM field WHERE field_id=%s"
        with conn.cursor() as cursor:
            cursor.execute(sql, field_id)
            field = cursor.fetchone()
        return render_template('field/update.html', field=field)


@mod.route('/delete/<field_id>', methods=['GET', 'POST'])
def delete(field_id):
    """刪除某筆field資料後,回到列表頁,或著只是將status改為False
    """
    conn = mysql.get_db()
    sql = u"DELETE FROM field WHERE `field_id`=%s"
    with conn.cursor() as cursor:
        conn.begin()
        cursor.execute(sql, field_id)
        conn.commit()
    return redirect(url_for('field.simple_list'))

project_name/templates/field/create.html
{% extends "index.html" %}
{% block body %}
<!-- Page heading -->
<div class="page-head">
	<h2 class="pull-left"><i class="fa fa-table"></i> 場地管理 </h2>

	<!-- Breadcrumb -->
	<div class="bread-crumb pull-right">
		<a href="{{ url_for('show_entries') }}"><i class="fa fa-home"></i> Home</a>
		<!-- Divider -->
		<span class="divider">/</span>
        <a href="{{ url_for('field.simple_list') }}"><i class="fa fa-home"></i>場地列表</a>
	</div>

	<div class="clearfix"></div>

</div>
<!-- Page heading ends -->

<!-- Matter -->
<div class="matter">
	<div class="container">
        <div class="row">
            <div class="col-md-7">
                <!-- Quick setting -->
                <div class="widget">
                    <div class="widget-head">
                      <div class="pull-left">新增場地</div>
                      <div class="widget-icons pull-right">
                        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                        <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <div class="padd">

                        <div class="form quick-post">
                            <!-- Quick setting form (not working)-->
                            <form class="form-horizontal" role="form" action="{{ url_for('field.create') }}" method="post">
                                <!-- Name -->
                                <div class="form-group">
                                    <label class="control-label col-md-2" for="fieldname"> 名稱</label>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control" id="fieldname" name="name" placeholder="請輸入場地名稱">
                                    </div>
                                </div>
                                <!-- Address -->
                                <div class="form-group">
                                    <label class="control-label col-md-2" for="fieldaddress"> 地點</label>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control" id="fieldaddress" name="address" placeholder="請輸入地址">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2"> Status</label>
                                    <div class="col-lg-7">
                                        <div class="sw-lblue">
                                            <div class="onoffswitch toggleBtn">
                                                <input name="status" id="onoffswitch1" class="toggleBtn onoffswitch-checkbox" checked="" type="checkbox">
                                                <label class="onoffswitch-label" for="onoffswitch1">
                                                    <span style="" class="onoffswitch-inner"></span>
                                                    <span style="" class="onoffswitch-switch"></span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Buttons -->
                                <div class="form-group">
                                    <!-- Buttons -->
                                    <div class="col-lg-9 col-lg-offset-2">
                                        <button type="submit" class="btn btn-info">Save Now</button>
                                        <button type="reset" class="btn btn-default">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        </div>
                        <div class="widget-foot">
                        <!-- Footer goes here -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project_name/templates/field/list.html
{% extends "index.html" %}
{% block body %}
<!-- Page heading -->
<div class="page-head">
	<h2 class="pull-left"><i class="fa fa-table"></i> 場地管理 </h2>
	<!-- Breadcrumb -->
	<div class="bread-crumb pull-right">
		<a href="{{ url_for('show_entries') }}"><i class="fa fa-home"></i> Home</a>
		<!-- Divider -->
		<span class="divider">/</span>
		<a href="{{ url_for('field.simple_list') }}" class="bread-current">場地列表</a>
	</div>

	<div class="clearfix"></div>

</div>
<!-- Page heading ends -->

<!-- Matter -->
<div class="matter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class="widget">
					<div class="widget-head">
						<div class="pull-left">場地列表</div>
						<div class="widget-icons pull-right">
							<a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
							<a href="#" class="wclose"><i class="fa fa-times"></i></a>
						</div>
						<div class="clearfix"></div>
					</div>

					<div class="widget-content">
                        <div class="padd">
                            <a href="{{ url_for('field.create') }}">
                                <button type="button" class="btn btn-sm btn-primary">
									<i class="fa fa-plus"></i>
									新增場地
								</button>
                            </a>
                        </div>

						<div class="padd">
							<div class="page-tables">
								<div class="table-responsive">
									<div class="dataTables_wrapper">
										<div class="dataTables_length" id="data-table-1_length">
											<label>Show
												<select id="select_page_items" name="data-table-1_length" aria-controls="data-table-1" class="" onChange="relocate(this);">
													<option value="10">10</option>
													<option value="25">25</option>
													<option value="50">50</option>
													<option value="100">100</option>
												</select>
												 entries
											</label>
										</div>
										<div id="data-table-1_filter" class="dataTables_filter">
											<form action="{{ url_for('field.search') }}" method="post">
												<label>Search:</label>
                                                <select id="s_key" name="s_key" aria-controls="data-table-1">
                                                    <option value="name">名稱</option>
                                                    <option value="address">地址</option>
                                                </select>
                                                <input name="s_value" type="search" placeholder="search for ..." aria-controls="data-table-1" value="{{ misc['s_value'] }}">
                                                <button type="submit" class="btn btn-sm btn-success">查詢</button>
												{% if misc['s_value'] %}
													<a class="btn btn-sm btn-danger" href="{{ url_for('field.simple_list') }}">取消</a>
												{% endif %}
											</form>
										</div>
										<table class="dataTable">
										  <thead>
											<tr>
											  <th class="sorting" id="name" onclick="resort(this)">場地名稱</th>
											  <th class="sorting" id="address" onclick="resort(this)">地址</th>
											  <th class="sorting" id="created" onclick="resort(this)">建立時間</th>
											  <th class="sorting" id="modified" onclick="resort(this)">編修時間</th>
											  <th class="sorting" id="status" onclick="resort(this)">狀態</th>
											  <th>Control</th>
											</tr>
										  </thead>
										  <tbody>
                                            {% for field in fields %}
											<tr>
												<td>{{ field[1] }}</td>
												<td>{{ field[2] }}</td>
												<td>{{ field[3]|strftime }}</td>
												<td>{{ field[4]|strftime }}</td>
												<td>
													{% if field[5]==1 %}
														<span class="label label-large label-success"><i class="fa fa-check"></i></span>
													{% else %}
														<span class="label label-large label-danger"><i class="fa fa-times"></i></span>
													{% endif %}
												</td>
												<td>
													<a href="{{ url_for('field.view', field_id=field[0]) }}">
														<button class="btn btn-xs btn-success"><i class="fa fa-eye"></i> </button>
													</a>
													<a href="{{ url_for('field.update', field_id=field[0]) }}">
														<button class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
													</a>
													<a href="{{ url_for('field.delete', field_id=field[0]) }}">
														<button class="btn btn-xs btn-danger"><i class="fa fa-times"></i> </button>
													</a>
												</td>
											</tr>
                                            {% endfor %}
										  </tbody>
										</table>
										<div class="dataTables_info" id="data-table-1_info" role="status" aria-live="polite">Showing {{ misc.start }} to {{ misc.end }} of {{ misc.total }} entries</div>
										<div class="dataTables_paginate paging_full_numbers">
											<a class="paginate_button" href="{{ url_for('field.' + action, page=0, items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">第一頁</a>
                                            <a class="paginate_button" href="{{ url_for('field.' + action, page=misc['prev'], items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">上一頁</a>
                                                <span>
                                                    {% for page_no in range(misc['paging_from'], misc['paging_to'] + 1) %}
                                                    <a class="paginate_button" href="{{ url_for('field.' + action, page=page_no, items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">{{ page_no + 1 }}</a>
                                                    {% endfor %}
                                                </span>
                                            <a class="paginate_button" href="{{ url_for('field.' + action, page=misc['next'], items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">下一頁</a>
                                            <a class="paginate_button" href="{{ url_for('field.' + action, page=misc['last'], items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">最後一頁</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Matter ends -->

<script>
//this part is about table sort and relocate
var page_url = "{{ url_for('field.' + action) }}";
var page_field = "{{misc['sort']}}";
var page_sort = {{misc['asc']}};
var page_items = {{misc['items']}};
var page_page = {{misc['page']}};

function relocate(){

	var item = document.getElementById("select_page_items");
	var item_val=item.options[item.selectedIndex].value;
	console.log(item_val);

	sort_table(page_url, page_field, page_sort, item_val, page_page);
}

function resort(element){
	var target_field = element.id;
	console.log(target_field);
	rsort_table(page_url, target_field, page_sort, page_items, page_page);
}

$(document).ready(function(){
    console.log('document ready');

	//change field class in thead
	sort_table_style(page_field,page_sort);

	//change pageitem selector to {{misc['items']}}
	var item = document.getElementById("select_page_items");
	for(var i=0 ; i<item.options.length ; i++) {
		if(item.options[i].value == page_items) {
			item.selectedIndex = i;
			break;
		}
	}

	//change search selector to {{misc['s_key']}}
	var item = document.getElementById("s_key");
	for(var i=0 ; i<item.options.length ; i++) {
		if(item.options[i].value == "{{ misc['s_key'] }}") {
			item.selectedIndex = i;
			break;
		}
	}

});
</script>
{% endblock %}

project_name/templates/field/update.html
{% extends "index.html" %}
{% block body %}
<!-- Page heading -->
<div class="page-head">
	<h2 class="pull-left"><i class="fa fa-table"></i> 場地管理 </h2>

	<!-- Breadcrumb -->
	<div class="bread-crumb pull-right">
		<a href="{{ url_for('show_entries') }}"><i class="fa fa-home"></i> Home</a>
		<!-- Divider -->
		<span class="divider">/</span>
        <a href="{{ url_for('field.simple_list') }}"><i class="fa fa-home"></i>場地列表</a>
	</div>

	<div class="clearfix"></div>

</div>
<!-- Page heading ends -->

<!-- Matter -->
<div class="matter">
	<div class="container">
        <div class="row">
            <div class="col-md-7">
                <!-- Quick setting -->
                <div class="widget">
                    <div class="widget-head">
                      <div class="pull-left">編修場地</div>
                      <div class="widget-icons pull-right">
                        <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                        <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <div class="padd">

                        <div class="form quick-post">
                            <!-- Quick setting form (not working)-->
                            <form class="form-horizontal" role="form" action="{{ url_for('field.update', field_id=field[0]) }}" method="post">
                                <!-- Name -->
                                <div class="form-group">
                                    <label class="control-label col-md-2" for="fieldname"> 名稱</label>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control" id="fieldname" name="name" value="{{ field[1] }}">
                                    </div>
                                </div>
                                <!-- ADdress -->
                                <div class="form-group">
                                    <label class="control-label col-md-2" for="fieldaddress"> 地址</label>
                                    <div class="col-md-7">
                                        <input type="text" class="form-control" id="fieldaddress" name="address" value="{{ field[2] }}">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2"> Status</label>
                                    <div class="col-lg-7">
                                        <div class="sw-lblue">
                                            <div class="onoffswitch toggleBtn">
                                                <input name="status" id="onoffswitch1" class="toggleBtn onoffswitch-checkbox" {% if field[5] %}checked=""{% endif%} type="checkbox">
                                                <label class="onoffswitch-label" for="onoffswitch1">
                                                    <span style="" class="onoffswitch-inner"></span>
                                                    <span style="" class="onoffswitch-switch"></span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Buttons -->
                                <div class="form-group">
                                    <!-- Buttons -->
                                    <div class="col-lg-9 col-lg-offset-2">
                                        <button type="submit" class="btn btn-info">Save Now</button>
                                        <button type="reset" class="btn btn-default">Reset</button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        </div>
                        <div class="widget-foot">
                        <!-- Footer goes here -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project_name/templates/field/view.html
{% extends "index.html" %}
{% block body %}
<!-- Page heading -->
<div class="page-head">
	<h2 class="pull-left"><i class="fa fa-table"></i> 場地管理 </h2>

	<!-- Breadcrumb -->
	<div class="bread-crumb pull-right">
		<a href="{{ url_for('show_entries') }}"><i class="fa fa-home"></i> Home</a>
		<!-- Divider -->
		<span class="divider">/</span>
        <a href="{{ url_for('field.simple_list') }}"><i class="fa fa-home"></i>場地列表</a>
	</div>

	<div class="clearfix"></div>

</div>
<!-- Page heading ends -->

<!-- Matter -->
<div class="matter">
	<div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="widget">
                    <!-- Widget title -->
                    <div class="widget-head">
                        <div class="pull-left">場地資訊</div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                            <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <!-- Widget content -->

                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <tbody>
                                    <tr>
                                        <td>名稱</td>
                                        <td>{{ field[1] }}</td>
                                    </tr>
                                    <tr>
                                        <td>地址</td>
                                        <td>{{ field[2] }}</td>
                                    </tr>
                                    <tr>
                                        <td>建立時間</td>
                                        <td>{{ field[3]|strftime }}</td>
                                    </tr>
                                    <tr>
                                        <td>編修時間</td>
                                        <td>{{ field[4]|strftime }}</td>
                                    </tr>
                                    <tr>
                                        <td>Status</td>
                                        <td>
                                            {% if field[5]==1 %}
                                                <span class="label label-success">On</span>
                                            {% else %}
                                                <span class="label label-danger">Off</span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Control</td>
                                        <td>
                                            <a href="{{ url_for('field.update', field_id=field[0]) }}">
                                                <button class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
                                            </a>
                                            <a href="{{ url_for('field.delete', field_id=field[0]) }}">
                                                <button class="btn btn-xs btn-danger"><i class="fa fa-times"></i> </button>
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="widget-foot"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}