project_name/views/ball.py
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import Blueprint, render_template, jsonify, redirect, url_for, request, g, session
from re import escape
from project_name.views.misc import items_pagebar
from project_name.extension import mysql

mod = Blueprint('ball', __name__)


@mod.route('/create/<play_id>', methods=['GET', 'POST'])
def create(play_id):
    """新增一筆ball資料
    """
    if request.method == 'POST':
        conn = mysql.get_db()
        sql = u"INSERT INTO `ball` (`play_id`, `ball_order`, `kind`, `speed`, `result`) VALUES (%s, %s, %s, %s, %s)"
        print(request.form.to_dict())
        post = request.form.to_dict()
        print(post)
        status = 'status' in request.form
        with conn.cursor() as cursor:
            conn.begin()
            cursor.execute(sql, (play_id,
            					post['ball_order'],
                                post['kind'],
                                post['speed'],
                                post['result'])
                           )
            conn.commit()
        return redirect(url_for('play.view', play_id=play_id))
    else:
        return render_template('ball/create.html', play_id=play_id)


@mod.route('/update/<play_id>/<ball_order>', methods=['GET', 'POST'])
def update(play_id, ball_order):
    """修改一筆ball資料
    若有post則修改後更新db
    無post則查出ball並顯示修改頁
    """
    conn = mysql.get_db()
    if request.method == 'POST':
        # 依 play_id 進行 update
        sql = u"UPDATE ball SET `kind`=%s, `speed`=%s, `result`=%s WHERE `play_id`=%s and `ball_order`=%s"
        print(request.form.to_dict())
        post = request.form.to_dict()
        status = 'status' in request.form
        with conn.cursor() as cursor:
            conn.begin()
            cursor.execute(sql, (post['kind'],
                                post['speed'],
                                post['result'],                      
                                play_id,
                                ball_order)
                           )
            conn.commit()
        return redirect(url_for('play.view', play_id=play_id, ball_order=ball_order))
    else:
        # 查出單筆, assign給頁面進行修改
        sql = u"SELECT * FROM ball WHERE `play_id`={0} and `ball_order`={1}".format(play_id, ball_order)
        with conn.cursor() as cursor:
            cursor.execute(sql)
            ball = cursor.fetchone()
        return render_template('ball/update.html', ball=ball)


@mod.route('/delete/<play_id>/<ball_order>', methods=['GET', 'POST'])
def delete(play_id, ball_order):
    """刪除某筆play資料後,回到列表頁
    """
    conn = mysql.get_db()
    sql = u"DELETE FROM ball WHERE `play_id`={0} and `ball_order`={1}".format(play_id, ball_order)
    with conn.cursor() as cursor:
        conn.begin()
        cursor.execute(sql)
        conn.commit()
    return redirect(url_for('play.simple_list'))

project_name/views/game.py
# -*- coding: utf-8 -*-
from datetime import datetime
from flask import Blueprint, render_template, jsonify, redirect, url_for, request, g, session
from re import escape
from project_name.views.misc import items_pagebar
from project_name.extension import mysql


mod = Blueprint('play', __name__)


@mod.route('/')
@mod.route('/simple_list', methods=['GET', 'POST'])
@mod.route('/simple_list/<int:page>/<int:items>', methods=['GET', 'POST'])
def simple_list(page=0, items=10):
    """簡單的game列表
    查出依條件查出 符合條件的資料
    可能有 LIMIT <from>,<how many>
    可能有 SORY BY <column> ASC/DESC
    然後 assign 給 html
    有一些經過標準計算取得的數值要 assign 給清單控制分頁用
    """
    conn = mysql.get_db()


    sql1 = u"SELECT COUNT(*) as total FROM play"
    # 先取得符合條件的 record 一共有多少筆
    with conn.cursor() as cursor:
        cursor.execute(sql1)
        row = cursor.fetchone()
        total = row[0]
    print(total)

    sort_condition = ""
    if 'sort' in request.args and 'asc' in request.args:  # 檢查是否同時提供排序的目標欄位及排序方法
        sort_condition = " ORDER BY {0} ".format(request.args.get('sort'))
        if request.args.get('asc') == '0':  # 表示不要asc, 即desc
            sort_condition += " DESC"
        else:  # 表示要asc
            sort_condition += " ASC"
    else:
        sort_condition = "ORDER BY play_id ASC"

    sql2 = "SELECT play_id, t1.player_name as pitcher_name, t2.player_name as batter_name, p.match_id, inning, half, M.m_date, F.name " \
           "FROM play p INNER JOIN player t1 ON t1.player_id = p.pitcher_id " \
           "INNER JOIN player t2 ON t2.player_id = p.batter_id " \
           "JOIN `match` AS M ON p.match_id = M.match_id " \
           "JOIN `field` AS F ON M.field_id = F.field_id " + sort_condition
    skip = page * items
    if skip >= total:
        skip = 0
    sql2 += " LIMIT {0},{1}".format(skip, items)
    print(sql2)

    # 執行 sql2 取得資料 (多筆)
    plays = []
    with conn.cursor() as cursor:
        cursor.execute(sql2)
        plays = cursor.fetchall()      
    print(plays)

    misc = items_pagebar(total, page, items, 'play_id')  # 計算pagebar需要之參數

    return render_template('play/list.html', plays=plays, misc=misc, action='simple_list')


@mod.route('/search', methods=['GET', 'POST'])
@mod.route('/search/<int:page>/<int:items>', methods=['GET', 'POST'])
def search(page=0, items=10):
    """加入搜尋條件的play列表
    """
    conn = mysql.get_db()
    query_condition = u""
    if request.method == 'POST' and request.form['s_key'] and request.form['s_value']:
        query_condition = u" WHERE {0} LIKE '%{1}%'".format(request.form['s_key'], request.form['s_value'])
        session['s_key'] = request.form['s_key']
        session['s_value'] = request.form['s_value']
    elif 's_key' in session and 's_value' in session:
        query_condition = u" WHERE {0} LIKE '%{1}%'".format(session['s_key'], session['s_value'])

    if len(query_condition) != 0:
        sql1 = u"SELECT COUNT(*) as total FROM play p " \
               u"INNER JOIN player t1 ON t1.player_id = p.pitcher_id " \
               u"INNER JOIN player t2 ON t2.player_id = p.batter_id " + query_condition
        with conn.cursor() as cursor:
            cursor.execute(sql1)
            row = cursor.fetchone()
            total = row[0]
        print(total)

        sort_condition = u""
        if 'sort' in request.args and 'asc' in request.args:
            sort_condition = u" ORDER BY {0} ".format(request.args.get('sort'))
            if request.args.get('asc') == '0':
                sort_condition += u" DESC"
            else:
                sort_condition += u" ASC"
        else:
            sort_condition = "ORDER BY play_id ASC"
                
        sql2 = u"SELECT play_id, t1.player_name as pitcher_name, t2.player_name as batter_name, match_id, inning, half " \
               u"FROM play p " \
               u"INNER JOIN player t1 ON t1.player_id = p.pitcher_id " \
               u"INNER JOIN player t2 ON t2.player_id = p.batter_id " + query_condition + sort_condition
        skip = page * items
        if skip >= total:
            skip = 0
        sql2 += u" LIMIT {0},{1}".format(skip, items)
        
        # 執行 sql2 取得資料 (多筆)
        plays = []
        with conn.cursor() as cursor:
            cursor.execute(sql2)
            plays = cursor.fetchall()
        print(plays)

        misc = items_pagebar(total, page, items, 'play_id')  # 計算pagebar需要之參數
        misc['s_key'] = session['s_key'] or u''
        misc['s_value'] = session['s_value'] or u''
        return render_template('play/list.html', plays=plays, misc=misc, action='search')
    else:
        return redirect(url_for('play.simple_list'))


@mod.route('/view/<play_id>')
def view(play_id):
    """顯示某筆play的頁面與細節
    """
    # 查出單筆, assign給頁面
    conn = mysql.get_db()
    sql = u"SELECT play_id, t1.player_name as pitcher_name, t2.player_name as batter_name, p.match_id, inning, half, M.m_date, F.name " \
          u"FROM play p INNER JOIN player t1 ON t1.player_id = p.pitcher_id " \
          u"INNER JOIN player t2 ON t2.player_id = p.batter_id " \
          u"JOIN `match` AS M ON p.match_id = M.match_id " \
          u"JOIN `field` AS F ON M.field_id = F.field_id " \
          u"WHERE p.play_id = %s"
    with conn.cursor() as cursor:
        cursor.execute(sql, play_id)
        play = cursor.fetchone()

    sql = u"SELECT ball.play_id, `ball_order`, `kind`, `speed`, `result` FROM play, ball WHERE ball.play_id=%s and play.play_id=ball.play_id "
    with conn.cursor() as cursor:
        cursor.execute(sql, play_id)
        balls = cursor.fetchall()
    return render_template('play/view.html', play=play, balls=balls)


@mod.route('/create', methods=['GET', 'POST'])
def create():
    """新增一筆play資料
    """
    if request.method == 'POST':
        conn = mysql.get_db()
        # 實際寫入一筆 t1.player_name as pitcher_name, t2.player_name as batter_name,
        sql = u"INSERT INTO `play` (`pitcher_id`, `batter_id`, `match_id`, `inning`, `half`) VALUES (%s, %s, %s, %s, %s)"
        print(request.form.to_dict())
        post = request.form.to_dict()
        print(post)
        status = 'status' in request.form
        with conn.cursor() as cursor:
            conn.begin()
            cursor.execute(sql, (post['pitcher_id'],
                                post['batter_id'],
                                post['match_id'],
                                post['inning'],
                                post['half'])
                           )
            play_id = cursor.lastrowid
            conn.commit()
        return redirect(url_for('play.view', play_id=play_id))
    else:
        conn = mysql.get_db()
        sql = u"SELECT match_id, m_date, field.name FROM `match` JOIN `field` ON match.field_id=field.field_id"
        with conn.cursor() as cursor:
            cursor.execute(sql)
            matches = cursor.fetchall()
        sql = u"SELECT * FROM player WHERE player_position='P'"
        with conn.cursor() as cursor:
            cursor.execute(sql)
            pitchers = cursor.fetchall()
        sql = u"SELECT * FROM player"
        with conn.cursor() as cursor:
            cursor.execute(sql)
            batters = cursor.fetchall()
        return render_template('play/create.html', matches=matches, pitchers=pitchers, batters=batters)


@mod.route('/update/<play_id>', methods=['GET', 'POST'])
def update(play_id):
    """修改一筆play資料
    若有post則修改後更新db
    無post則查出player並顯示修改頁
    """
    conn = mysql.get_db()
    if request.method == 'POST':
        # 依 play_id 進行 update
        sql = u"UPDATE play SET `pitcher_id`=%s, `batter_id`=%s, `match_id`=%s, `inning`=%s, `half`=%s WHERE `play_id`=%s"
        print(request.form.to_dict())
        post = request.form.to_dict()
        status = 'status' in request.form
        with conn.cursor() as cursor:
            conn.begin()
            cursor.execute(sql, (post['pitcher_id'],
                                post['batter_id'],
                                post['match_id'],
                                post['inning'],
                                post['half'],                      
                                play_id)
                           )
            conn.commit()
        return redirect(url_for('play.view', play_id=play_id))
    else:
        # 查出單筆, assign給頁面進行修改
        sql = u"SELECT * FROM play WHERE play_id=%s"
        with conn.cursor() as cursor:
            cursor.execute(sql, play_id)
            play = cursor.fetchone()
        conn = mysql.get_db()
        sql = u"SELECT match_id, m_date, field.name FROM `match` JOIN `field` ON match.field_id=field.field_id"
        with conn.cursor() as cursor:
            cursor.execute(sql)
            matches = cursor.fetchall()
        sql = u"SELECT * FROM player WHERE player_position='P'"
        with conn.cursor() as cursor:
            cursor.execute(sql)
            pitchers = cursor.fetchall()
        sql = u"SELECT * FROM player"
        with conn.cursor() as cursor:
            cursor.execute(sql)
            batters = cursor.fetchall()
        return render_template('play/update.html', play=play, matches=matches, pitchers=pitchers, batters=batters)


@mod.route('/delete/<play_id>', methods=['GET', 'POST'])
def delete(play_id):
    """刪除某筆play資料後,回到列表頁
    """
    conn = mysql.get_db()
    sql = u"DELETE FROM play WHERE `play_id`=%s"
    with conn.cursor() as cursor:
        conn.begin()
        cursor.execute(sql, play_id)
        conn.commit()
    return redirect(url_for('play.simple_list'))

project_name/templates/play/list.html
{% extends "index.html" %}
{% block body %}
<!-- Page heading -->
<div class="page-head">
	<h2 class="pull-left"><i class="fa fa-table"></i> 打席管理 </h2>
	<!-- Breadcrumb -->
	<div class="bread-crumb pull-right">
		<a href="{{ url_for('show_entries') }}"><i class="fa fa-home"></i> Home</a>
		<!-- Divider -->
		<span class="divider">/</span>
		<a href="{{ url_for('play.simple_list') }}" class="bread-current">打席列表</a>
	</div>

	<div class="clearfix"></div>

</div>
<!-- Page heading ends -->

<!-- Matter -->
<div class="matter">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

				<div class="widget">
					<div class="widget-head">
						<div class="pull-left">打席列表</div>
						<div class="widget-icons pull-right">
							<a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
							<a href="#" class="wclose"><i class="fa fa-times"></i></a>
						</div>
						<div class="clearfix"></div>
					</div>

					<div class="widget-content">
                        <div class="padd">
                            <a href="{{ url_for('play.create') }}">
                                <button type="button" class="btn btn-sm btn-primary">
									<i class="fa fa-plus"></i>
									新增打席
								</button>
                            </a>
                        </div>

						<div class="padd">
							<div class="page-tables">
								<div class="table-responsive">
									<div class="dataTables_wrapper">
										<div class="dataTables_length" id="data-table-1_length">
											<label>Show
												<select id="select_page_items" name="data-table-1_length" aria-controls="data-table-1" class="" onChange="relocate(this);">
													<option value="10">10</option>
													<option value="25">25</option>
													<option value="50">50</option>
													<option value="100">100</option>
												</select>
												 entries
											</label>
										</div>
										<div id="data-table-1_filter" class="dataTables_filter">
											<form action="{{ url_for('play.search') }}" method="post">
												<label>Search:</label>
                                                <select id="s_key" name="s_key" aria-controls="data-table-2">
                                                    <option value="play_id">打席ID</option>
                                                    <option value="t1.player_name">投手名稱</option>
                                                    <option value="t2.player_name">打者名稱</option>
                                                    <option value="match_id">比賽場次</option>
                                                    <option value="inning">第幾局</option>
                                                </select>
                                                <input name="s_value" type="search" placeholder="search for ..." aria-controls="data-table-1" value="{{ misc['s_value'] }}">
                                                <button type="submit" class="btn btn-sm btn-success">查詢</button>
												{% if misc['s_value'] %}
													<a class="btn btn-sm btn-danger" href="{{ url_for('play.simple_list') }}">取消</a>
												{% endif %}
											</form>
										</div>
										<table class="dataTable">
										  <thead>
											<tr>
											  <th class="sorting" id="play_id" onclick="resort(this)">打席ID</th>
											  <th class="sorting" id="pitcher_id" onclick="resort(this)">投手名稱</th>
											  <th class="sorting" id="batter_id" onclick="resort(this)">打者名稱</th>
											  <th class="sorting" id="match_id" onclick="resort(this)">比賽場次</th>
											  <th class="sorting" id="inning" onclick="resort(this)">第幾局</th>
											  <th class="sorting" id="half" onclick="resort(this)">上下半場</th>
											  <th>Control</th>
											</tr>
										  </thead>
										  <tbody>
                                            {% for play in plays %}
											<tr>
												<td>{{ play[0] }}</td>
												<td>{{ play[1] }}</td>
												<td>{{ play[2] }}</td>
												<td>match:{{ play[3] }} on {{ play[6] }} @ {{ play[7] }}</td>
												<td>{{ play[4] }}</td>
												<td>
													{% if play[5] == 'TOP'%}
													上半場
													{% else %}
													下半場
													{% endif%}
												</td>
												
												<td>
													<a href="{{ url_for('play.view', play_id=play[0]) }}">
														<button class="btn btn-xs btn-success"><i class="fa fa-eye"></i> </button>
													</a>
													<a href="{{ url_for('play.update', play_id=play[0]) }}">
														<button class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
													</a>
													<a href="{{ url_for('play.delete', play_id=play[0]) }}">
														<button class="btn btn-xs btn-danger"><i class="fa fa-times"></i> </button>
													</a>
												</td>
											</tr>
                                            {% endfor %}
										  </tbody>
										</table>
										<div class="dataTables_info" id="data-table-1_info" role="status" aria-live="polite">Showing {{ misc.start }} to {{ misc.end }} of {{ misc.total }} entries</div>
										<div class="dataTables_paginate paging_full_numbers">
											<a class="paginate_button" href="{{ url_for('play.' + action, page=0, items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">第一頁</a>
                                            <a class="paginate_button" href="{{ url_for('play.' + action, page=misc['prev'], items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">上一頁</a>
                                                <span>
                                                    {% for page_no in range(misc['paging_from'], misc['paging_to'] + 1) %}
                                                    <a class="paginate_button" href="{{ url_for('play.' + action, page=page_no, items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">{{ page_no + 1 }}</a>
                                                    {% endfor %}
                                                </span>
                                            <a class="paginate_button" href="{{ url_for('play.' + action, page=misc['next'], items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">下一頁</a>
                                            <a class="paginate_button" href="{{ url_for('play.' + action, page=misc['last'], items=misc['items'], sort=misc['sort'], asc=misc['asc']) }}">最後一頁</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Matter ends -->

<script>
//this part is about table sort and relocate
var page_url = "{{ url_for('play.' + action) }}";
var page_field = "{{misc['sort']}}";
var page_sort = {{misc['asc']}};
var page_items = {{misc['items']}};
var page_page = {{misc['page']}};

function relocate(){

	var item = document.getElementById("select_page_items");
	var item_val=item.options[item.selectedIndex].value;
	console.log(item_val);

	sort_table(page_url, page_field, page_sort, item_val, page_page);
}

function resort(element){
	var target_field = element.id;
	console.log(target_field);
	rsort_table(page_url, target_field, page_sort, page_items, page_page);
}

$(document).ready(function(){
    console.log('document ready');

	//change field class in thead
	sort_table_style(page_field,page_sort);

	//change pageitem selector to {{misc['items']}}
	var item = document.getElementById("select_page_items");
	for(var i=0 ; i<item.options.length ; i++) {
		if(item.options[i].value == page_items) {
			item.selectedIndex = i;
			break;
		}
	}

	//change search selector to {{misc['s_key']}}
	var item = document.getElementById("s_key");
	for(var i=0 ; i<item.options.length ; i++) {
		if(item.options[i].value == "{{ misc['s_key'] }}") {
			item.selectedIndex = i;
			break;
		}
	}

});
</script>
{% endblock %}

project_name/templates/play/view.html
{% extends "index.html" %}
{% block body %}
<!-- Page heading -->
<div class="page-head">
	<h2 class="pull-left"><i class="fa fa-table"></i> 打席管理 </h2>

	<!-- Breadcrumb -->
	<div class="bread-crumb pull-right">
		<a href="{{ url_for('show_entries') }}"><i class="fa fa-home"></i> Home</a>
		<!-- Divider -->
		<span class="divider">/</span>
        <a href="{{ url_for('play.simple_list') }}"><i class="fa fa-home"></i>打席列表</a>
	</div>

	<div class="clearfix"></div>

</div>
<!-- Page heading ends -->

<!-- Matter -->
<div class="matter">
	<div class="container">
        <div class="row">
            <div class="col-md-7">
                <div class="widget">
                    <!-- Widget title -->
                    <div class="widget-head">
                        <div class="pull-left">打席資訊</div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                            <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content">
                        <!-- Widget content -->
                        <div class="widget-head">
                            <a href="{{ url_for('ball.create', play_id=play[0]) }}">
                                <button type="button" class="btn btn-sm btn-primary">
                                    <i class="fa fa-plus"></i>
                                    新增逐球
                                </button>
                            </a>
                    </div>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <tbody>
                                    <tr>
                                        <td>打席ID</td>
                                        <td>{{ play[0] }}</td>
                                    </tr>
                                    <tr>
                                        <td>投手名稱</td>
                                        <td>{{ play[1] }}</td>
                                    </tr>
                                    <tr>
                                        <td>打者名稱</td>
                                        <td>{{ play[2] }}</td>
                                    </tr>
                                    <tr>
                                        <td>比賽場次</td>
                                        <td>match:{{ play[3] }} on {{play[6]}} @ {{play[7]}}</td>
                                    </tr>
                                    <tr>
                                        <td>第幾局</td>
                                        <td>{{ play[4] }}</td>
                                    </tr>
                                    <tr>
                                        <td>上下半場</td>
                                        <td>
                                            {% if play[5] == 'TOP'%}
                                            上半場
                                            {% else %}
                                            下半場
                                            {% endif%}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Control</td>
                                        <td>
                                            <a href="{{ url_for('play.update', play_id=play[0]) }}">
                                                <button class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
                                            </a>
                                            <a href="{{ url_for('play.delete', play_id=play[0]) }}">
                                                <button class="btn btn-xs btn-danger"><i class="fa fa-times"></i> </button>
                                            </a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th class="sorting" id="play_id" onclick="resort(this)">打席ID</th>
                                        <th class="sorting" id="ball_order" onclick="resort(this)">第幾球</th>
                                        <th class="sorting" id="kind" onclick="resort(this)">球種</th>
                                        <th class="sorting" id="spped" onclick="resort(this)">球速</th>
                                        <th class="sorting" id="result" onclick="resort(this)">結果</th>
                                        <th>Control</th>
                                    </tr>
                                </thead>
                                    <tbody>
                                        {% for ball in balls %}
                                            <tr>
                                                <td>{{ ball[0] }}</td>
                                                <td>{{ ball[1] }}</td>
                                                <td>{{ ball[2] }}</td>
                                                <td>{{ ball[3] }}</td>
                                                <td>{{ ball[4] }}</td>
                                                <td>
                                                    <a href="{{ url_for('ball.update', play_id=ball[0], ball_order=ball[1]) }}">
                                                        <button class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
                                                    </a>
                                                    <a href="{{ url_for('ball.delete', play_id=ball[0], ball_order=ball[1]) }}">
                                                        <button class="btn btn-xs btn-danger"><i class="fa fa-times"></i> </button>
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                            </table>
                        </div>
                        <div class="widget-foot"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}